name: CD
on:
  push:
    branches:
      - master
      - main

jobs:
  # flutter_test:
  #   name: Run flutter test and analyze
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.8"
  #     - name: create .env file
  #       env:
  #         API_URL: ${{ secrets.API_URL }}
  #         SECRET: ${{ secrets.SECRET }}
  #       run: python scripts/create_env.py
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter analyze
  #     - run: flutter test

  build_appbundle:
    name: Build Flutter (Android)
    # needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: create .env file
        env:
          API_URL: ${{ secrets.API_URL }}
          SECRET: ${{ secrets.SECRET }}
        run: python scripts/create_env.py
      - name: change build number
        env:
          BUILD_NUM: ${{github.run_number}}
        run: python scripts/change_build_number.py
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Create Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEY_JKS_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: net.cloudphotos.www
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal

  build_ios:
    name: Build Flutter (iOS)
    # needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Folder for certificates and profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/MobileDevice/Certificates/

      - name: Get Certificate
        id: certFileDecode
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'certificate.p12'
          encodedString: ${{ secrets.P12_BASE64 }}
      - name: Copy Certificate
        run: mv ${{ steps.certFileDecode.outputs.filePath }} ~/Library/MobileDevice/Certificates/certificate.p12
       
      - name: Get Profile
        id: profFileDecode
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'decoded.mobileprovision'
          encodedString: ${{ secrets.MOBILEPROVISION_BASE64 }}
      - name: Copy Profiles
        run: mv ${{ steps.profFileDecode.outputs.filePath }} ~/Library/MobileDevice/Provisioning\ Profiles/decoded.mobileprovision

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install python dependencies
        run:  python -m pip install codemagic-cli-tools
      - name: Initialize Keychain with certificate
        run: |
          keychain initialize
          keychain add-certificates --certificate ~/Library/MobileDevice/Certificates/certificate.p12 --certificate-password ${{ secrets.cert_password }}
      - name: create .env file
        env:
          API_URL: ${{ secrets.API_URL }}
          SECRET: ${{ secrets.SECRET }}
        run: python scripts/create_env.py
      - name: change build number
        env:
          BUILD_NUM: ${{github.run_number}}
        run: python scripts/change_build_number.py
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: |
         xcode-project use-profiles
         flutter build ios --release --no-codesign
         xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release

      # - name: collect ipa artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: adhoc-ipa
      #     # Path to the release files
      #     path: build/ios/ipa/*.ipa

      - name: Upload app to App Store Connect
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f build/ios/ipa/cloud_photos_v2.ipa -u "$APP_STORE_CONNECT_USERNAME" -p "$APP_STORE_CONNECT_PASSWORD"